/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

object App {
  def main(args: Array[String]): Unit = {
    var x = "test"
    x = "x"
    println(greeting())
  }

  def greeting(): String = "Hello, world!"
}
