#!/usr/bin/env python3
###############################################################################
# Copyright (c) 2022 Marc Schreiber and others.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
# Marc Schreiber - initial API and implementation
###############################################################################
import importlib.util
import sys
import os

script_dir = os.path.dirname(os.path.realpath(__file__))
file_path = os.path.join(script_dir, "jdtls.py")

spec = importlib.util.spec_from_file_location("jdtls", file_path)
jdtls = importlib.util.module_from_spec(spec)
sys.modules["jdtls"] = jdtls
spec.loader.exec_module(jdtls)

jdtls.main(sys.argv[1:])
