/*******************************************************************************
 * Copyright (c) 2026 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Angelo ZERR - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.ls.core.internal.mbt;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Stream;

import org.eclipse.core.resources.ICommand;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.IProjectDescription;
import org.eclipse.core.resources.IWorkspace;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.OperationCanceledException;
import org.eclipse.core.runtime.SubMonitor;
import org.eclipse.jdt.core.IAccessRule;
import org.eclipse.jdt.core.IClasspathAttribute;
import org.eclipse.jdt.core.IClasspathEntry;
import org.eclipse.jdt.core.IJavaProject;
import org.eclipse.jdt.core.JavaCore;
import org.eclipse.jdt.ls.core.internal.AbstractProjectImporter;
import org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin;
import org.eclipse.jdt.ls.core.internal.ResourceUtils;
import org.eclipse.jdt.ls.core.internal.ServiceStatus;
import org.eclipse.jdt.ls.core.internal.managers.OnDemandImportManager;

/**
 * Imports projects from an {@code mbt.json} file, a standard format originated
 * by Metals V2 and generated by the classpath-extractor project.
 *
 * <p>This importer is registered with {@code order=10}, running before
 * Maven (400) and Gradle (300). When {@code mbt.json} is detected,
 * it blocks the native importers via {@link #isResolved}.</p>
 *
 * <p>Two modes are supported, controlled by a preference setting:
 * <ul>
 *   <li><b>full</b>: all targets are imported at {@code initialize}</li>
 *   <li><b>ondemand</b>: only a source-folder index is built at
 *       {@code initialize}; modules are imported on
 *       {@code textDocument/didOpen}</li>
 * </ul>
 */
public class MbtProjectImporter extends AbstractProjectImporter {

	public static final String MBT_MODE_FULL = "full";
	public static final String MBT_MODE_ONDEMAND = "ondemand";

	private volatile MbtInfo mbtInfo;
	private volatile MbtSourceFolderIndex mbtIndex;
	private Path workspacePath;
	private boolean mbtDetected;
	private volatile boolean perModuleMode;
	private Map<String, Path> artifactIdToDir;

	@Override
	public boolean applies(IProgressMonitor monitor) throws OperationCanceledException, CoreException {
		if (rootFolder == null || !isMbtEnabled()) {
			return false;
		}
		workspacePath = rootFolder.toPath().toAbsolutePath().normalize();
		Path mbtJsonPath = MbtJson.getPath(workspacePath);

		if (Files.isRegularFile(mbtJsonPath)) {
			mbtDetected = true;
			return true;
		}

		mbtDetected = hasBuildFiles(workspacePath);
		return mbtDetected;
	}

	@Override
	public void importToWorkspace(IProgressMonitor monitor) throws OperationCanceledException, CoreException {
		if (!mbtDetected) {
			return;
		}
		SubMonitor subMonitor = SubMonitor.convert(monitor, 100);

		Path mbtJsonPath = MbtJson.getPath(workspacePath);
		String mode = getMbtMode();

		// On-demand mode without mbt.json: activate immediately with per-module generation
		// and start background generation of the full mbt.json
		if (MBT_MODE_ONDEMAND.equals(mode) && !Files.isRegularFile(mbtJsonPath)) {
			perModuleMode = true;
			mbtInfo = new MbtInfo();
			mbtIndex = new MbtSourceFolderIndex(mbtInfo, workspacePath);
			OnDemandImportManager.getInstance().activate(this, null, workspacePath);
			JavaLanguageServerPlugin.logInfo("On-demand mode: per-module MBT generation active, modules will be resolved on didOpen");
			subMonitor.worked(100);
			return;
		}

		// Step 1: Generate or read mbt.json
		boolean persistToFile = getPreferences().isMbtStorageFile();
		if (!Files.isRegularFile(mbtJsonPath)) {
			subMonitor.subTask("Generating mbt.json...");
			JavaLanguageServerPlugin.logInfo("Generating mbt.json for workspace: " + workspacePath);
			try {
				mbtInfo = MbtExtractor.generate(workspacePath, persistToFile, subMonitor.split(50));
			} catch (IOException e) {
				JavaLanguageServerPlugin.logException("Failed to generate mbt.json", e);
				return;
			}
		} else {
			JavaLanguageServerPlugin.logInfo("Using existing mbt.json: " + mbtJsonPath);
			try {
				mbtInfo = MbtJson.read(mbtJsonPath);
			} catch (IOException e) {
				JavaLanguageServerPlugin.logException("Failed to read mbt.json", e);
				return;
			}
			subMonitor.worked(50);
		}
		subMonitor.worked(5);

		if (mbtInfo == null || mbtInfo.getNamespaces().isEmpty()) {
			JavaLanguageServerPlugin.logInfo("mbt.json contains no targets");
			return;
		}

		// Step 3: Build source folder index (always needed, lightweight)
		subMonitor.subTask("Building source folder index...");
		JavaLanguageServerPlugin.logInfo("Building source folder index for " + mbtInfo.getNamespaces().size() + " targets");
		mbtIndex = new MbtSourceFolderIndex(mbtInfo, workspacePath);
		subMonitor.worked(5);

		// Step 4: Import according to mode
		if (MBT_MODE_FULL.equals(mode)) {
			importAllTargets(subMonitor.split(40));
		} else {
			OnDemandImportManager.getInstance().activate(this, null, null);
			JavaLanguageServerPlugin.logInfo("On-demand mode: skipping full import, modules will be loaded on didOpen");
			subMonitor.worked(40);
		}
	}

	/**
	 * Import all targets from mbt.json (full mode).
	 */
	private void importAllTargets(IProgressMonitor monitor) throws CoreException {
		Map<String, MbtTargetInfo> namespaces = mbtInfo.getNamespaces();
		int targetCount = namespaces.size();
		SubMonitor subMonitor = SubMonitor.convert(monitor, targetCount * 2);

		JavaLanguageServerPlugin.logInfo("Importing all " + targetCount + " targets from mbt.json (full mode)");

		List<String> targetIds = new ArrayList<>(namespaces.keySet());
		Map<String, IProject> projects = new HashMap<>();

		// Pass 1: Create/open all projects with Java nature
		subMonitor.subTask("Creating projects...");
		JavaLanguageServerPlugin.logInfo("Pass 1: Creating " + targetIds.size() + " projects...");
		for (String targetId : targetIds) {
			if (subMonitor.isCanceled()) {
				throw new OperationCanceledException();
			}
			String projectName = toProjectName(targetId);
			subMonitor.subTask("Creating project: " + projectName);
			IProject project = createOrOpenProject(targetId, namespaces.get(targetId));
			if (project != null) {
				projects.put(targetId, project);
			}
			subMonitor.worked(1);
		}

		// Pass 2: Configure classpath in topological order (leaves first)
		subMonitor.subTask("Configuring classpaths...");
		List<String> sorted = topologicalSort(projects.keySet(), namespaces);
		JavaLanguageServerPlugin.logInfo("Pass 2: Configuring classpaths for " + projects.size() + " projects (topological order)...");
		MbtBuildSupport buildSupport = new MbtBuildSupport();
		buildSupport.setMbtInfo(mbtInfo);
		buildSupport.setWorkspacePath(workspacePath);
		for (String id : sorted) {
			if (subMonitor.isCanceled()) {
				throw new OperationCanceledException();
			}
			IProject project = projects.get(id);
			if (project == null) {
				continue;
			}
			String projectName = toProjectName(id);
			subMonitor.subTask("Configuring classpath: " + projectName);
			try {
				buildSupport.update(project, true, subMonitor.split(1));
			} catch (CoreException e) {
				JavaLanguageServerPlugin.logException("Failed to configure classpath for " + projectName, e);
			}
		}

		mbtIndex.markImported(targetIds);
		JavaLanguageServerPlugin.logInfo("MBT import complete: " + projects.size() + " projects configured");
	}

	@Override
	public List<IProject> importOnDemand(String uri, IProgressMonitor monitor) throws CoreException {
		if (mbtIndex == null) {
			return List.of();
		}
		org.eclipse.core.runtime.IPath filePath = ResourceUtils.canonicalFilePathFromURI(uri);
		if (filePath == null) {
			return List.of();
		}
		Path javaFilePath = Path.of(filePath.toOSString());
		String targetId = mbtIndex.findTarget(javaFilePath);

		// Per-module generation: if target not found, generate MBT for this module
		if (targetId == null) {
			if (!generateModuleOnDemand(javaFilePath, monitor)) {
				return List.of();
			}
			targetId = mbtIndex.findTarget(javaFilePath);
		}

		if (targetId == null || mbtIndex.isImportedAsProject(targetId)) {
			return List.of();
		}

		if (mbtIndex.isImportedAsLibrary(targetId)) {
			return promoteLibraryTarget(targetId, monitor);
		}

		List<String> toImport = mbtIndex.collectTargetsToImport(targetId);
		if (toImport.isEmpty()) {
			return List.of();
		}

		// Split: primary target gets IProject, deps with target/classes use CPE_LIBRARY
		List<String> projectTargets = new ArrayList<>();
		List<String> libraryTargets = new ArrayList<>();
		for (String id : toImport) {
			if (id.equals(targetId)) {
				projectTargets.add(id);
			} else {
				MbtTargetInfo depTarget = mbtInfo.getNamespaces().get(id);
				if (depTarget != null && hasClassesOutput(depTarget)) {
					libraryTargets.add(id);
				} else {
					projectTargets.add(id);
				}
			}
		}

		SubMonitor subMonitor = SubMonitor.convert(monitor, projectTargets.size() * 2);
		JavaLanguageServerPlugin.logInfo("On-demand import: " + projectTargets.size()
				+ " project(s) + " + libraryTargets.size() + " library dep(s) triggered by " + targetId);

		Map<String, IProject> projects = new HashMap<>();

		// Pass 1: Create projects only for targets that need IProject
		for (String id : projectTargets) {
			if (subMonitor.isCanceled()) {
				throw new OperationCanceledException();
			}
			String projectName = toProjectName(id);
			subMonitor.subTask("Creating project: " + projectName);
			IProject project = createOrOpenProject(id, mbtInfo.getNamespaces().get(id));
			if (project != null) {
				projects.put(id, project);
			}
			subMonitor.worked(1);
		}

		// Pass 2: Configure classpath (buildClasspathEntries handles library deps via CPE_LIBRARY)
		List<String> sorted = topologicalSort(projects.keySet(), mbtInfo.getNamespaces());
		MbtBuildSupport buildSupport = new MbtBuildSupport();
		buildSupport.setMbtInfo(mbtInfo);
		buildSupport.setWorkspacePath(workspacePath);
		for (String id : sorted) {
			if (subMonitor.isCanceled()) {
				throw new OperationCanceledException();
			}
			IProject project = projects.get(id);
			if (project == null) {
				continue;
			}
			String projectName = toProjectName(id);
			subMonitor.subTask("Configuring classpath: " + projectName);
			try {
				buildSupport.update(project, true, subMonitor.split(1));
			} catch (CoreException e) {
				JavaLanguageServerPlugin.logException("Failed to configure classpath for " + projectName, e);
			}
		}

		mbtIndex.markImported(projectTargets);
		mbtIndex.markImportedAsLibrary(libraryTargets);
		JavaLanguageServerPlugin.logInfo("On-demand import complete: " + projects.size()
				+ " projects created, " + libraryTargets.size() + " deps as libraries");
		return new ArrayList<>(projects.values());
	}

	/**
	 * Promotes a library target to a full IProject. Called when the user
	 * opens a file from a dependency that was previously imported as a
	 * CPE_LIBRARY (target/classes).
	 */
	private List<IProject> promoteLibraryTarget(String targetId, IProgressMonitor monitor) throws CoreException {
		MbtTargetInfo target = mbtInfo.getNamespaces().get(targetId);
		if (target == null) {
			return List.of();
		}

		JavaLanguageServerPlugin.logInfo("Promoting library target to project: " + targetId);
		IProject project = createOrOpenProject(targetId, target);
		if (project == null) {
			return List.of();
		}

		MbtBuildSupport buildSupport = new MbtBuildSupport();
		buildSupport.setMbtInfo(mbtInfo);
		buildSupport.setWorkspacePath(workspacePath);
		buildSupport.update(project, true, monitor);

		mbtIndex.promoteToProject(targetId);

		// Update existing projects that had this target as CPE_LIBRARY → now CPE_PROJECT
		int updated = 0;
		for (String depId : mbtIndex.getDirectDependents(targetId)) {
			if (!mbtIndex.isImportedAsProject(depId)) {
				continue;
			}
			String depProjectName = toProjectName(depId);
			IProject depProject = ResourcesPlugin.getWorkspace().getRoot().getProject(depProjectName);
			if (depProject.exists() && depProject.isOpen()) {
				try {
					buildSupport.update(depProject, true, monitor);
					updated++;
				} catch (CoreException e) {
					JavaLanguageServerPlugin.logException(
							"Failed to update classpath for " + depProjectName + " after promotion", e);
				}
			}
		}

		JavaLanguageServerPlugin.logInfo("Library target promoted to project: " + targetId
				+ " (" + updated + " dependent project(s) updated)");
		return List.of(project);
	}

	private boolean hasClassesOutput(MbtTargetInfo target) {
		for (String classesDir : target.getClasses()) {
			Path classesPath = workspacePath.resolve(classesDir).normalize();
			if (Files.isDirectory(classesPath)) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Generates MBT info for the module containing the given file path,
	 * resolving its dependencies via Maven. Cascades to unresolved SNAPSHOT
	 * reactor dependencies so that inter-module references compile.
	 *
	 * @return {@code true} if generation succeeded and targets were registered
	 */
	private boolean generateModuleOnDemand(Path filePath, IProgressMonitor monitor) {
		Path moduleDir = findModuleDir(filePath);
		if (moduleDir == null) {
			return false;
		}
		try {
			Set<String> generatedDirs = new HashSet<>();
			Set<String> newTargetIds = new HashSet<>();

			generateModuleWithCascade(moduleDir, generatedDirs, newTargetIds, monitor);

			if (newTargetIds.isEmpty()) {
				return false;
			}

			// Promote dependency modules that became targets after cascade
			mbtInfo.promoteTargets();

			// Register all new targets in the index (with promoted dependsOn)
			for (String targetId : newTargetIds) {
				MbtTargetInfo target = mbtInfo.getNamespaces().get(targetId);
				if (target != null) {
					mbtIndex.addTarget(targetId, target, workspacePath);
				}
			}

			MbtExtractor.clearHierarchyCaches();

			JavaLanguageServerPlugin.logInfo("Per-module MBT generation complete: "
					+ newTargetIds.size() + " target(s)");
			return true;
		} catch (IOException e) {
			JavaLanguageServerPlugin.logException("Failed to generate MBT for module: " + moduleDir, e);
			return false;
		}
	}

	private void generateModuleWithCascade(Path moduleDir, Set<String> generatedDirs,
			Set<String> newTargetIds, IProgressMonitor monitor) throws IOException {
		MbtInfo moduleInfo = generateSingleModule(moduleDir, generatedDirs, newTargetIds, monitor);
		if (moduleInfo == null) {
			return;
		}

		// Cascade one level: resolve direct SNAPSHOT reactor dependencies
		Collection<MbtDependencyModuleInfo> deps = moduleInfo.getDependencyModules();
		for (MbtDependencyModuleInfo dep : deps) {
			String id = dep.getId();
			if (id != null && id.endsWith("-SNAPSHOT")) {
				String artifactId = extractArtifactId(id);
				Path depModuleDir = findModuleDirForArtifact(artifactId);
				if (depModuleDir != null) {
					generateSingleModule(depModuleDir, generatedDirs, newTargetIds, monitor);
				}
			}
		}
	}

	private MbtInfo generateSingleModule(Path moduleDir, Set<String> generatedDirs,
			Set<String> newTargetIds, IProgressMonitor monitor) throws IOException {
		String moduleDirKey = moduleDir.normalize().toString();
		if (!generatedDirs.add(moduleDirKey)) {
			return null;
		}

		JavaLanguageServerPlugin.logInfo("Per-module MBT generation for: " + moduleDir);
		JavaLanguageServerPlugin.sendStatus(ServiceStatus.Message,
				"Resolving module: " + moduleDir.getFileName());

		MbtInfo moduleInfo = MbtExtractor.generateForModule(moduleDir, workspacePath, monitor);
		if (moduleInfo == null || moduleInfo.getNamespaces().isEmpty()) {
			return null;
		}

		mbtInfo.merge(moduleInfo);
		newTargetIds.addAll(moduleInfo.getNamespaces().keySet());
		return moduleInfo;
	}

	private Path findModuleDirForArtifact(String artifactId) {
		if (artifactId == null) {
			return null;
		}
		if (artifactIdToDir == null) {
			artifactIdToDir = buildArtifactIdIndex();
		}
		return artifactIdToDir.get(artifactId);
	}

	private Map<String, Path> buildArtifactIdIndex() {
		Map<String, Path> index = new HashMap<>();
		try (Stream<Path> walk = Files.walk(workspacePath)) {
			walk.filter(p -> "pom.xml".equals(p.getFileName().toString()))
				.filter(p -> {
					String s = p.toString();
					return !s.contains(File.separator + "target" + File.separator)
						&& !s.contains(File.separator + ".git" + File.separator);
				})
				.forEach(pomPath -> {
					String aid = extractArtifactIdFromPom(pomPath);
					if (aid != null) {
						index.put(aid, pomPath.getParent());
					}
				});
		} catch (IOException e) {
			JavaLanguageServerPlugin.logException("Failed to build artifactId index", e);
		}
		JavaLanguageServerPlugin.logInfo("ArtifactId index built: " + index.size() + " modules");
		return index;
	}

	private static String extractArtifactIdFromPom(Path pomPath) {
		try {
			String content = Files.readString(pomPath);
			int parentStart = content.indexOf("<parent>");
			int parentEnd = content.indexOf("</parent>");
			if (parentStart >= 0 && parentEnd > parentStart) {
				content = content.substring(0, parentStart)
						+ content.substring(parentEnd + "</parent>".length());
			}
			int start = content.indexOf("<artifactId>");
			if (start >= 0) {
				start += "<artifactId>".length();
				int end = content.indexOf("</artifactId>", start);
				if (end > start) {
					return content.substring(start, end).trim();
				}
			}
		} catch (IOException e) {
			// ignore unreadable pom
		}
		return null;
	}

	private static String extractArtifactId(String gavId) {
		if (gavId == null) {
			return null;
		}
		String[] parts = gavId.split(":");
		return parts.length >= 2 ? parts[1] : null;
	}

	/**
	 * Walks up the directory tree from the given file path to find the
	 * nearest directory containing a build file (pom.xml or build.gradle).
	 */
	private Path findModuleDir(Path filePath) {
		Path current = filePath.getParent();
		while (current != null && current.startsWith(workspacePath)) {
			if (Files.isRegularFile(current.resolve("pom.xml"))
					|| Files.isRegularFile(current.resolve("build.gradle"))) {
				return current;
			}
			current = current.getParent();
		}
		return null;
	}

	/**
	 * Creates or opens an Eclipse IProject for the given mbt target.
	 */
	private IProject createOrOpenProject(String targetId, MbtTargetInfo target) throws CoreException {
		if (target == null) {
			return null;
		}
		String projectName = toProjectName(targetId);
		IWorkspace workspace = ResourcesPlugin.getWorkspace();
		IProject project = workspace.getRoot().getProject(projectName);

		if (!project.exists()) {
			// Resolve project location from source folders
			Path projectPath = resolveProjectPath(target);
			if (projectPath == null) {
				JavaLanguageServerPlugin.logInfo("Skipping target with no sources: " + targetId);
				return null;
			}

			// Check for overlapping location (e.g. main/test scopes share the same directory)
			IProject overlapping = findProjectAtLocation(workspace, projectPath);
			if (overlapping != null) {
				JavaLanguageServerPlugin.logInfo("Skipping target " + targetId
						+ ": location overlaps with existing project '" + overlapping.getName() + "'");
				return null;
			}

			IProjectDescription description = workspace.newProjectDescription(projectName);
			description.setLocation(org.eclipse.core.runtime.Path.fromOSString(projectPath.toString()));
			description.setNatureIds(new String[] { JavaCore.NATURE_ID });
			try {
				project.create(description, null);
			} catch (CoreException e) {
				JavaLanguageServerPlugin.logException("Failed to create project " + projectName, e);
				return null;
			}
		}

		if (!project.isOpen()) {
			project.open(null);
		}

		// Remove Maven/Gradle natures from previous sessions so that
		// MavenBuildSupport/GradleBuildSupport no longer applies.
		stripBuildSystemNatures(project);

		ensureJavaBuilder(project);

		return project;
	}

	/**
	 * Finds an existing workspace project whose location matches the given path.
	 */
	private static IProject findProjectAtLocation(IWorkspace workspace, Path location) {
		Path normalized = location.normalize();
		for (IProject p : workspace.getRoot().getProjects()) {
			if (p.getLocation() != null) {
				Path existing = p.getLocation().toFile().toPath().normalize();
				if (existing.equals(normalized)) {
					return p;
				}
			}
		}
		return null;
	}

	private static final Set<String> BUILD_SYSTEM_NATURES = Set.of(
			"org.eclipse.m2e.core.maven2Nature",
			"org.eclipse.buildship.core.gradleprojectnature");

	private void stripBuildSystemNatures(IProject project) throws CoreException {
		IProjectDescription description = project.getDescription();
		String[] oldNatures = description.getNatureIds();
		List<String> kept = new ArrayList<>();
		for (String nature : oldNatures) {
			if (!BUILD_SYSTEM_NATURES.contains(nature)) {
				kept.add(nature);
			}
		}
		if (kept.size() == oldNatures.length) {
			return;
		}
		if (!kept.contains(JavaCore.NATURE_ID)) {
			kept.add(0, JavaCore.NATURE_ID);
		}
		description.setNatureIds(kept.toArray(String[]::new));
		project.setDescription(description, null);
		JavaLanguageServerPlugin.logInfo("Stripped build-system natures from " + project.getName());
	}

	private static final String JAVA_BUILDER_ID = "org.eclipse.jdt.core.javabuilder";

	private void ensureJavaBuilder(IProject project) throws CoreException {
		IProjectDescription description = project.getDescription();
		ICommand[] buildSpec = description.getBuildSpec();
		for (ICommand cmd : buildSpec) {
			if (JAVA_BUILDER_ID.equals(cmd.getBuilderName())) {
				return;
			}
		}
		ICommand javaBuilder = description.newCommand();
		javaBuilder.setBuilderName(JAVA_BUILDER_ID);
		ICommand[] newSpec = new ICommand[buildSpec.length + 1];
		newSpec[0] = javaBuilder;
		System.arraycopy(buildSpec, 0, newSpec, 1, buildSpec.length);
		description.setBuildSpec(newSpec);
		project.setDescription(description, null);
		JavaLanguageServerPlugin.logInfo("Added Java builder to " + project.getName());
	}

	/**
	 * Resolves the project root path from the target's source folders.
	 * Uses the common parent of all source folders.
	 */
	private Path resolveProjectPath(MbtTargetInfo target) {
		List<String> sources = target.getSources();
		if (sources.isEmpty()) {
			return null;
		}
		// Use the first source's module root (e.g. "module/src/main/java" → "module")
		Path firstSource = workspacePath.resolve(sources.get(0)).normalize();
		// Walk up from source folder to find the module root
		// Convention: src/main/java → 3 levels up, src/test/java → 3 levels up
		Path current = firstSource;
		while (current != null && !current.equals(workspacePath)) {
			Path pomXml = current.resolve("pom.xml");
			Path buildGradle = current.resolve("build.gradle");
			if (Files.exists(pomXml) || Files.exists(buildGradle)) {
				return current;
			}
			current = current.getParent();
		}
		// Fallback: parent of the source folder structure
		return firstSource.getParent();
	}

	@Override
	public boolean isResolved(File folder) throws OperationCanceledException, CoreException {
		if (perModuleMode) {
			return true;
		}
		return mbtInfo != null && !mbtInfo.getNamespaces().isEmpty();
	}

	@Override
	public void onMbtJsonReady(MbtInfo fullMbtInfo) {
		if (fullMbtInfo == null || fullMbtInfo.getNamespaces().isEmpty()) {
			return;
		}
		MbtSourceFolderIndex fullIndex = new MbtSourceFolderIndex(fullMbtInfo, workspacePath);
		Set<String> imported = mbtIndex.getImportedTargets();
		if (!imported.isEmpty()) {
			fullIndex.markImported(new ArrayList<>(imported));
		}
		Set<String> libraries = mbtIndex.getLibraryTargets();
		if (!libraries.isEmpty()) {
			fullIndex.markImportedAsLibrary(new ArrayList<>(libraries));
		}
		mbtIndex = fullIndex;
		mbtInfo = fullMbtInfo;
		perModuleMode = false;
		JavaLanguageServerPlugin.logInfo("Switched to full mbt.json: "
				+ fullMbtInfo.getNamespaces().size() + " targets, "
				+ imported.size() + " already imported");
	}

	@Override
	public void reset() {
		OnDemandImportManager.getInstance().deactivate();
		mbtInfo = null;
		mbtIndex = null;
		mbtDetected = false;
		perModuleMode = false;
	}

	@Override
	public boolean supportsOnDemand() {
		return true;
	}

	@Override
	public boolean importReverseDependencies(String uri, boolean forModification, IProgressMonitor monitor) throws CoreException {
		if (mbtIndex == null || mbtInfo == null) {
			return false;
		}
		org.eclipse.core.runtime.IPath filePath = ResourceUtils.canonicalFilePathFromURI(uri);
		if (filePath == null) {
			return false;
		}
		String targetId = mbtIndex.findTarget(Path.of(filePath.toOSString()));
		if (targetId == null) {
			return false;
		}
		List<String> reverseDeps = mbtIndex.collectReverseDependencies(targetId);
		if (reverseDeps.isEmpty()) {
			return false;
		}

		if (!forModification) {
			return importReverseDepsAsLibrary(targetId, reverseDeps, monitor);
		}
		return importReverseDepsAsProjects(targetId, reverseDeps, monitor);
	}

	/**
	 * Library mode: adds reverse deps' {@code target/classes} as CPE_LIBRARY
	 * entries on the current project's classpath with non-accessible access rules.
	 * Used for Find References — fast, no IProject creation, no JDT build.
	 */
	private boolean importReverseDepsAsLibrary(String targetId, List<String> reverseDeps,
			IProgressMonitor monitor) throws CoreException {
		String projectName = toProjectName(targetId);
		IProject currentProject = ResourcesPlugin.getWorkspace().getRoot().getProject(projectName);
		if (!currentProject.exists() || !currentProject.isOpen()) {
			return false;
		}
		IJavaProject javaProject = JavaCore.create(currentProject);

		IAccessRule[] restrictRules = new IAccessRule[] {
			JavaCore.newAccessRule(new org.eclipse.core.runtime.Path("**"), IAccessRule.K_NON_ACCESSIBLE)
		};

		// Collect existing classpath paths to avoid duplicates
		IClasspathEntry[] currentCp = javaProject.getRawClasspath();
		Set<String> existingPaths = new HashSet<>();
		for (IClasspathEntry entry : currentCp) {
			existingPaths.add(entry.getPath().toOSString());
		}

		List<IClasspathEntry> newEntries = new ArrayList<>();
		List<String> addedDeps = new ArrayList<>();
		List<String> fallbackDeps = new ArrayList<>();
		for (String depId : reverseDeps) {
			MbtTargetInfo depTarget = mbtInfo.getNamespaces().get(depId);
			if (depTarget == null) {
				continue;
			}
			if (!hasClassesOutput(depTarget)) {
				fallbackDeps.add(depId);
				continue;
			}
			int entriesBefore = newEntries.size();
			for (String classesDir : depTarget.getClasses()) {
				Path classesPath = workspacePath.resolve(classesDir).normalize();
				if (!Files.isDirectory(classesPath)) {
					continue;
				}
				org.eclipse.core.runtime.IPath classesIPath =
						org.eclipse.core.runtime.Path.fromOSString(classesPath.toString());
				if (existingPaths.contains(classesIPath.toOSString())) {
					continue;
				}
				org.eclipse.core.runtime.IPath sourceAttachment = null;
				for (String source : depTarget.getSources()) {
					Path sourcePath = workspacePath.resolve(source).normalize();
					if (Files.isDirectory(sourcePath)) {
						sourceAttachment = org.eclipse.core.runtime.Path.fromOSString(sourcePath.toString());
						break;
					}
				}
				newEntries.add(JavaCore.newLibraryEntry(classesIPath, sourceAttachment, null,
						restrictRules, new IClasspathAttribute[0], false));
			}
			if (newEntries.size() > entriesBefore) {
				addedDeps.add(depId);
			}
		}

		// Fallback: reverse deps without target/classes need IProject for search
		if (!fallbackDeps.isEmpty()) {
			JavaLanguageServerPlugin.logInfo("Reverse deps (library mode): "
					+ fallbackDeps.size() + " dep(s) without target/classes, falling back to project mode");
			importReverseDepsAsProjects(targetId, fallbackDeps, monitor);
		}

		if (newEntries.isEmpty()) {
			return !fallbackDeps.isEmpty();
		}

		IClasspathEntry[] updated = new IClasspathEntry[currentCp.length + newEntries.size()];
		System.arraycopy(currentCp, 0, updated, 0, currentCp.length);
		for (int i = 0; i < newEntries.size(); i++) {
			updated[currentCp.length + i] = newEntries.get(i);
		}
		javaProject.setRawClasspath(updated, monitor);
		mbtIndex.markImportedAsLibrary(addedDeps);

		JavaLanguageServerPlugin.logInfo("Reverse deps (library mode): added "
				+ newEntries.size() + " CPE_LIBRARY entries from "
				+ addedDeps.size() + " reverse dep(s) on " + projectName);
		return true;
	}

	/**
	 * Project mode: creates IProject for each reverse dep so that source files
	 * can be modified. Used for Rename.
	 */
	private boolean importReverseDepsAsProjects(String targetId, List<String> reverseDeps,
			IProgressMonitor monitor) throws CoreException {
		Set<String> allTargets = new java.util.LinkedHashSet<>();
		for (String depId : reverseDeps) {
			List<String> transitive = mbtIndex.collectTargetsToImport(depId);
			allTargets.addAll(transitive);
			if (!mbtIndex.isImportedAsProject(depId)) {
				allTargets.add(depId);
			}
		}
		if (allTargets.isEmpty()) {
			return false;
		}

		Set<String> reverseDepSet = new java.util.LinkedHashSet<>(reverseDeps);
		List<String> projectTargets = new ArrayList<>();
		List<String> libTargets = new ArrayList<>();
		for (String id : allTargets) {
			if (reverseDepSet.contains(id)) {
				projectTargets.add(id);
			} else {
				MbtTargetInfo t = mbtInfo.getNamespaces().get(id);
				if (t != null && hasClassesOutput(t)) {
					libTargets.add(id);
				} else {
					projectTargets.add(id);
				}
			}
		}

		JavaLanguageServerPlugin.logInfo("Importing " + reverseDeps.size()
				+ " reverse dependencies (project mode): " + projectTargets.size()
				+ " project(s) + " + libTargets.size()
				+ " library dep(s) for " + targetId);

		SubMonitor subMonitor = SubMonitor.convert(monitor, projectTargets.size() * 2);
		Map<String, IProject> projects = new HashMap<>();
		int count = 0;
		int total = projectTargets.size();

		for (String id : projectTargets) {
			if (subMonitor.isCanceled()) {
				break;
			}
			count++;
			String pName = toProjectName(id);
			String msg = "Importing reverse deps [" + count + "/" + total + "]: " + pName;
			subMonitor.subTask(msg);
			JavaLanguageServerPlugin.sendStatus(ServiceStatus.Message, msg);
			MbtTargetInfo target = mbtInfo.getNamespaces().get(id);
			if (target != null) {
				IProject project = createOrOpenProject(id, target);
				if (project != null) {
					projects.put(id, project);
				}
			}
			subMonitor.worked(1);
		}

		List<String> sorted = topologicalSort(projects.keySet(), mbtInfo.getNamespaces());
		MbtBuildSupport buildSupport = new MbtBuildSupport();
		buildSupport.setMbtInfo(mbtInfo);
		buildSupport.setWorkspacePath(workspacePath);
		count = 0;
		for (String id : sorted) {
			if (subMonitor.isCanceled()) {
				break;
			}
			IProject project = projects.get(id);
			if (project == null) {
				continue;
			}
			count++;
			String pName = toProjectName(id);
			String msg = "Configuring classpath [" + count + "/" + sorted.size() + "]: " + pName;
			subMonitor.subTask(msg);
			JavaLanguageServerPlugin.sendStatus(ServiceStatus.Message, msg);
			try {
				buildSupport.update(project, true, subMonitor.split(1));
			} catch (CoreException e) {
				JavaLanguageServerPlugin.logException("Failed to configure classpath for " + pName, e);
			}
		}

		for (String id : projectTargets) {
			if (mbtIndex.isImportedAsLibrary(id)) {
				mbtIndex.promoteToProject(id);
				for (String depId : mbtIndex.getDirectDependents(id)) {
					if (!mbtIndex.isImportedAsProject(depId)) {
						continue;
					}
					String depProjectName = toProjectName(depId);
					IProject depProject = ResourcesPlugin.getWorkspace().getRoot().getProject(depProjectName);
					if (depProject.exists() && depProject.isOpen() && !projects.containsKey(depId)) {
						try {
							buildSupport.update(depProject, true, monitor);
						} catch (CoreException e) {
							JavaLanguageServerPlugin.logException(
									"Failed to update classpath for " + depProjectName + " after promotion", e);
						}
					}
				}
			} else {
				mbtIndex.markImported(List.of(id));
			}
		}
		if (!libTargets.isEmpty()) {
			mbtIndex.markImportedAsLibrary(libTargets);
		}
		JavaLanguageServerPlugin.logInfo("Reverse dependency import complete (project mode): "
				+ projects.size() + " project(s), " + libTargets.size() + " library dep(s)");
		return !projects.isEmpty();
	}


	/**
	 * Converts a target ID (e.g. "org.acme:my-module:1.0:main") to a simple
	 * project name (e.g. "my-module").
	 */
	static String toProjectName(String targetId) {
		// Format: groupId:artifactId:version:scope
		String[] parts = targetId.split(":");
		if (parts.length >= 2) {
			String artifactId = parts[1];
			String scope = parts.length >= 4 ? parts[3] : "main";
			if ("test".equals(scope)) {
				return artifactId + "-test";
			}
			return artifactId;
		}
		return targetId;
	}

	private boolean isMbtEnabled() {
		var preferencesManager = JavaLanguageServerPlugin.getPreferencesManager();
		if (preferencesManager == null) {
			return false;
		}
		return preferencesManager.getPreferences().isImportMbtEnabled();
	}

	private String getMbtMode() {
		var preferencesManager = JavaLanguageServerPlugin.getPreferencesManager();
		if (preferencesManager != null) {
			String mode = preferencesManager.getPreferences().getImportMode();
			if (MBT_MODE_ONDEMAND.equals(mode)) {
				return MBT_MODE_ONDEMAND;
			}
		}
		return MBT_MODE_FULL;
	}

	/**
	 * Sorts targets in topological order (dependencies first) so that each
	 * project's classpath is configured after its dependsOn projects.
	 * This avoids "prerequisite X is not built" errors from JDT's incremental
	 * builder, which fires after each setRawClasspath() call.
	 *
	 * Example: quarkus-netty-deployment dependsOn [quarkus-netty, quarkus-arc-deployment]
	 *   → quarkus-netty and quarkus-arc-deployment are configured first,
	 *     then quarkus-netty-deployment.
	 */
	private static List<String> topologicalSort(Set<String> targetIds, Map<String, MbtTargetInfo> namespaces) {
		List<String> result = new ArrayList<>(targetIds.size());
		Set<String> visited = new HashSet<>();
		Set<String> scope = new HashSet<>(targetIds);
		for (String id : targetIds) {
			topoVisit(id, namespaces, scope, visited, result);
		}
		return result;
	}

	private static void topoVisit(String id, Map<String, MbtTargetInfo> namespaces,
			Set<String> scope, Set<String> visited, List<String> result) {
		if (!visited.add(id)) {
			return;
		}
		MbtTargetInfo target = namespaces.get(id);
		if (target != null) {
			for (String dep : target.getDependsOn()) {
				if (scope.contains(dep)) {
					topoVisit(dep, namespaces, scope, visited, result);
				}
			}
		}
		result.add(id);
	}

	private boolean hasBuildFiles(Path dir) {
		try (var stream = Files.find(dir, 3,
				(path, attrs) -> attrs.isRegularFile()
						&& ("pom.xml".equals(path.getFileName().toString())
								|| "build.gradle".equals(path.getFileName().toString())))) {
			return stream.findFirst().isPresent();
		} catch (IOException e) {
			return false;
		}
	}
}
