/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fbricon' at '24/10/16 11:28' with Gradle 3.0
 *
 * @author fbricon, @date 24/10/16 11:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
