/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.twelve;

import org.junit.Test;

import foo.bar.Foo;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	assertEquals("Zero", Foo.main(null));
    }
}
